# Introduction to Python - day 5 - numpy and pandas
### Gyan Krishna - 534 
### Date - 19/9/2022

## Homogenous arrays

In [13]:
import array
arr = array.array('i', [1,2,3,4])
print(arr)
print(type(arr))

array('i', [1, 2, 3, 4])
<class 'array.array'>


## Intro to numpy

In [3]:
import numpy as np
np.__version__

'1.15.4'

## Creation of numpy array and attributes 

In [71]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.itemsize)
print(arr.nbytes)
print(type(arr))

[1 2 3 4 5]
1
5
(5,)
4
20
<class 'numpy.ndarray'>


## data type of numpy arrays

In [69]:
a = np.array([1,2,3.0, 4.0]) #everything made float
b = np.array([1,2,3.0, 4.0], dtype = 'float32')
c = np.array([1,2,3.0, 4.0], dtype = np.int)
print(type(a))
print(a)
print(b)
print(c)

<class 'numpy.ndarray'>
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1 2 3 4]


## multidimensional arrays

In [28]:
x = np.array([range(i, i+3) for i in [2,4,6]])
print(x)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


## creation of arrays

In [68]:
x = np.zeros(4, dtype = 'int')
print(x)
print('-'*50)

y = np.ones(3, dtype = 'float32')
print(y)
print('-'*50)

z = np.full((3,5), 3.14) #creating filled array
print(z)
print('-'*50)

a = np.arange(0, 20, 2) 
print(a)
print('-'*50)

b = np.linspace(0, 1, 5) #0, 1, = interval ; 5 = no of samples
print(b)
print('-'*50)

np.random.seed(5)
c = np.random.random((3,3)) # random b/w 0-1
print(c)
print('-'*50)

d = np.random.randint(0, 10, (4, 4)) # random array of dimm 4x4 with numbers b/w 0 and 1
print(d)
print('-'*50)

e = np.random.normal(0, 1, (3,3)) # resuultant array will have, mean = 0, sd = 1 , array dimm = 3x3
print(d)
print(d.mean())
print('-'*50)

f = np.eye(4, dtype = np.int) # identity matrix 
print(f) 

[0 0 0 0]
--------------------------------------------------
[1. 1. 1.]
--------------------------------------------------
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
--------------------------------------------------
[ 0  2  4  6  8 10 12 14 16 18]
--------------------------------------------------
[0.   0.25 0.5  0.75 1.  ]
--------------------------------------------------
[[0.22199317 0.87073231 0.20671916]
 [0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005 ]]
--------------------------------------------------
[[1 5 7 0]
 [1 4 6 2]
 [9 9 9 9]
 [1 2 7 0]]
--------------------------------------------------
[[1 5 7 0]
 [1 4 6 2]
 [9 9 9 9]
 [1 2 7 0]]
4.5
--------------------------------------------------
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Array indexing and slicing

In [88]:
arr = np.array(range(9))
print(arr)

print(arr[1: 6: 2]) # start:end:step
print(arr[:5])      # first 5 elements 
print(arr[::2])     # alternative elements from start to end  
print(arr[2::2])    # altenate elements from 2 to end 

print(arr[-1])      # -ve indexing 
print(arr[::-1])    # reverse order
print(arr[5::-1])   # revrse order from index 5
print('-'*50)

mat = arr.reshape((3,3))
print(mat[:2, :3])
print('-'*50)

print(mat[:3, ::2]) #
print('-'*50)

print(mat[::-1, ::-1])
print('-'*50)

[0 1 2 3 4 5 6 7 8]
[1 3 5]
[0 1 2 3 4]
[0 2 4 6 8]
[2 4 6 8]
8
[8 7 6 5 4 3 2 1 0]
[5 4 3 2 1 0]
--------------------------------------------------
[[0 1 2]
 [3 4 5]]
--------------------------------------------------
[[0 2]
 [3 5]
 [6 8]]
--------------------------------------------------
[[8 7 6]
 [5 4 3]
 [2 1 0]]
--------------------------------------------------


## sub arrays as no copy views

Changes made in sub array will reflect in the original array

In [91]:
arr = np.array(range(9))
arr = arr.reshape((3,3))
arr_sub = arr[:2, :2]

print(arr_sub)
arr_sub[0,0] = 99

print(arr)

[[0 1]
 [3 4]]
[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]


## Array reshaping

In [96]:
arr = np.arange(1, 10)
mat = arr.reshape((3,3))

print(arr)
print(mat)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array concatenation

In [113]:
x = np.arange(0, 3)
y = np.arange(3, 6)
z = np.array([99, 99, 99])
p = np.arange(0, 9).reshape(3,3)

print(x, y)
print(np.concatenate([x, y]))
print(np.concatenate([x, y, z], axis = 0)) # try axis = 1 for 2d array

print(np.vstack([p, x]))
print('-'*50)

#print(np.hstack([p, x]))
#print('-'*50)

[0 1 2] [3 4 5]
[0 1 2 3 4 5]
[ 0  1  2  3  4  5 99 99 99]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]]
--------------------------------------------------


## Array splitting

In [116]:
a = np.arange(0, 9)
x, y, z = np.split(a, [3, 5])  # split as 0-3, 3-5, 5-end
print(x, y, z)

mat = np.arange(0, 9).reshape(3,3)
print(mat)
upper, lower = np.vsplit(mat, [2])
print(upper, lower)

[0 1 2] [3 4] [5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]] [[6 7 8]]


## UFuncs
used to quickly exec repeated opr on values of np arrays, <br>
Ufunc can be unary or binary

various u func are
> np.add <br>
> np.multiply <br>
> np.substract <br>
... etc

In [122]:
x = np.arange(4)
print(x)
print(x + 5)
print(x - 5)
print(x * 5)
print(x / 5)
print(x // 5)
print(x % 5)
print(x ** 5)
print(x % 5)


print( -(0.5*x + 1)**2 )

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]
[0 0 0 0]
[0 1 2 3]
[  0   1  32 243]
[0 1 2 3]
[-1.   -2.25 -4.   -6.25]
